### ISSUE TITLE
Support group shortname in w3c.json in addition to group id

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/validate-repos#107]
The definition of w3c.json is being [amended to support either shortnames or ids](https://github.com/w3c/w3c.github.io/pull/104) for the `group` field - the repo validator should support both

**Comment by vivienlacourba** [comment]
In addition to the PR #108 please also update https://w3c.github.io/w3c.json.html#group

Are you planning to update all existing `w3c.json` files to use shortnames instead of Ids?

**Comment by dontcallmedom** [comment]
https://github.com/w3c/w3c.github.io/pull/104 was already drafted, pending resolution of this issue

**Comment by dontcallmedom** [comment]
> Are you planning to update all existing w3c.json files to use shortnames instead of Ids?

Not at this stage, since the code supports both. Updating several hundred of repos with different editing policies across multiple orgs is not something I would recommend without a strong motivation.
