### ISSUE TITLE
ash-nagz checks

### ISSUE THREAD

**Issue by plehegar** [w3c/validate-repos#15]
ash-nazg contains information about repositories that is no longer valid. We should flag those.

**Comment by dontcallmedom** [comment]
The latest release checks when a repo is associated in ash-nazg to a group different from the on in w3c.json.

We could check if there is an inconsistency between the repo and the latest TR as well, but it's probably more dicey:
* we don't know how to associate a repo to a spec when there are multiple specs in a given repo
* a technical report remains associated with its old group until it is republished by the new group
