### ISSUE TITLE
Include a check for .pr-preview.json

### ISSUE THREAD

**Issue by plehegar** [w3c/validate-repos#16]
This tool also diffs to be generated on PRs. We need to check if that file is properly configured.

**Comment by tripu** [comment]
Are we recommending [PR Preview](https://github.com/tobie/pr-preview) officially now?

**Comment by plehegar** [comment]
we kind of did a while ago. The service is stable and Tobie is fine with keeping alive. However, if we do want some improvements, we'll have to contribute.

**Comment by tripu** [comment]
I'm OK if we check for this config file just to show an informative note, not to recommend this tool (W3C staff have not developed it nor have experience maintaining it, it is hosted outside our systems where we can't manage it, and the author has made it explicit that he does not plan to maintain it *pro bono*).

**Comment by dontcallmedom** [comment]
this got done in 05fc397dc48abc506125685c65d5512afd29a43b
