### ISSUE TITLE
Update 'master' branch, make it the default one, switch GH Pages there, and remove 'gh-pages' branch?

### ISSUE THREAD

**Issue by tripu** [w3c/validate-repos#3]

**Comment by dontcallmedom** [comment]
in general, I prefer keeping separate the generating system (in `master`) and its outpout (in `gh-pages`) - could you elaborate why you suggest keeping only one branch?

Thanks!

**Comment by tripu** [comment]
Ah, I see, you're using one for the code, another one for the report?
But the HTML is identical, in both branches. It's only `report.js` and `report.json` that are different between the branches.
Isn't it a bother to keep track of changes and propagate among branches, as opposed to having all together?
Just a matter of opinion :)

**Comment by dontcallmedom** [comment]
right `report.html` is the same, and `report.js` ought to be the same :)

not much of a bother in practice - just a matter of running `git merge master`.

closing the issue

**Comment by tripu** [comment]
Okay!

(FYI, [`report.js` isn't the same in both branches](https://github.com/w3c/validate-repos/compare/master...gh-pages#diff-8fa4cfdbaa51e010dbe9124e0e7392c2))
