### ISSUE TITLE
Build report from GitHub Actions

### ISSUE THREAD

**Issue by foolip** [w3c/validate-repos#32]
Just like https://github.com/tidoust/reffy-reports/pull/39 this would make it easier for non-maintainers (me!) to understand the setup and verify that they work locally before sending PRs.

**Comment by foolip** [comment]
Now done!

**Comment by foolip** [comment]
Reopening because @dontcallmedom also needs to turn off his cron job. Both ran this last midnight and https://github.com/w3c/validate-repos/runs/300257121 failed because when it had finished master had changed.

However, the push to master by @dontcallmedom-bot triggered another run: https://github.com/w3c/validate-repos/runs/300262443

That resulted in commit df21f2082621c38c6dbb494005bf02ad3f61d55c which appears to revert some changes from the parent commit aabd041fe2aadc077eea1e941aa62915d15bc71a. It's able to find more labels, it seems.

@dontcallmedom do you know what accounts for these differences? Understanding this before turning off your cron job is probably a good idea.

**Comment by dontcallmedom** [comment]
I turned off the cron job this morning; I can't really explain the differences though.

**Comment by foolip** [comment]
If you run the script again now on the same machine that ran the cron job with the same token, does that still do the removals in https://github.com/w3c/validate-repos/commit/aabd041fe2aadc077eea1e941aa62915d15bc71a?

**Comment by dontcallmedom** [comment]
nope, it doesn't - I also ran an npm install beforehand which may have had something with the inconsistency? anyway, I think we're good
