### ISSUE TITLE
Label extraction is unreliable

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/validate-repos#67]
From one run to the next, the list of labels extracted varies without good reason (e.g. https://github.com/w3c/validate-repos/commit/04043af092a5df5836ecae15f43b57fe697296b4#diff-76a84217c1c1e1d7ecf1a6de26061bb3 ).

**Comment by foolip** [comment]
What could be happening here is network errors or rate limts causing some requests to fail. Such failures are just logged without returning a non-zero exit code. I'd argue it's better to fail in such cases, and if it happens too much due to network errors add a retry mechanism.

**Comment by foolip** [comment]
I expect that https://github.com/w3c/validate-repos/pull/79 should have fixed this, but looking at report.json since then there are some ordering changes. I'll send a PR to sort the labels so that any real changes stand out better.

**Comment by foolip** [comment]
f1d1005763343dd15273a231f16a8e4e2efc85a5 had a lot of changes as expected, let's wait a bit and see if labels still seems to pop in and out of the report for no good reason.

**Comment by plehegar** [comment]
I would note that the GH API seems to be in a good mood today. No weird changes in https://github.com/w3c/validate-repos/commit/39443aed36f3eb5b24ac016024e729a5dc49fe01#diff-76a84217c1c1e1d7ecf1a6de26061bb3

**Comment by plehegar** [comment]
btw, in case someone is curious, I'm using like
 https://www.w3.org/2019/10/gh-labels.html?gtype=working&search=i18n
to track consistency of labels across repos. I guess I could move that page in this repo (it involved overtime so didn't think of it before)

**Comment by foolip** [comment]
https://github.com/w3c/validate-repos/commit/fcea505f69f7af2f0e606bceef774c21f0f7bc93 also didn't have any suspect differences around labels, so I'd consider this fixed.

**Comment by dontcallmedom** [comment]
Unfortunately, it seems this has re-surfaced the issue we had previous running the job, with non-descript failures of the graphql queries:
 https://github.com/w3c/validate-repos/commit/fcea505f69f7af2f0e606bceef774c21f0f7bc93/checks?check_suite_id=367672758
(this has failed the past 2 days, and failed when I relaunched it manually this morning)

**Comment by foolip** [comment]
@dontcallmedom has this sort of thing still been happening? Maybe smaller requests are needed?

**Comment by dontcallmedom** [comment]
there have been a few streaks of failures, but nothing worrisome recently, so I think we can keep things as is for now.
