### ISSUE TITLE
Merge both branches?

### ISSUE THREAD

**Issue by tripu** [w3c/validate-repos#7]
[`master` is ahead of `gh-pages` by one commit right now](https://github.com/w3c/validate-repos/compare/gh-pages...master) (may I rebase `gh-pages`?)

Since `master` will always be a direct ascendant of `gh-pages` (ie, it won't contain changes itself), why not keep just `master`, and have both types of commits (humans contributing to the code, and the bot regenerating the report) going to the same branch?

**Comment by dontcallmedom** [comment]
I've merged both branches as you suggested
