### ISSUE TITLE
Check specs are served over https

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/validate-repos#70]
[https is not enforced as the scheme for github pages created before June 2016](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https) and has to be manually set in the repo settings. We should ensure all relevant repos have that setting enabled.

**Comment by foolip** [comment]
I can't see this in https://developer.github.com/v3/repos/pages/ or the GraphQL API. Since it's just few hundred repos, maybe it'd be easiest to just open the right URLs in tabs and go through them all, checking the box where not checked?

**Comment by dontcallmedom** [comment]
looking a bit more into it, we have 431 repos that were created before the cut-off date according to report.json - that's beyond my motivation :)

I've wrote a little script that instead looks at the repos created before the date and with an `homepageUrl` set (reducing it to ~230 repos) and testing if the said URL responds with a 301 (which repos set to force-https do). The result is that at least the following repos needs fixing:
* [ ] https://github.com/immersive-web/webvr-polyfill/settings
* [ ] https://github.com/w3c/activitypub/settings
* [ ] https://github.com/w3c/ambient-light/settings
* [ ] https://github.com/w3c/aria/settings
* [ ] https://github.com/w3c/aria-practices/settings
* [ ] https://github.com/w3c/cg-charter/settings
* [ ] https://github.com/w3c/charmod-norm/settings
* [ ] https://github.com/w3c/charter-html/settings
* [ ] https://github.com/w3c/charter-timed-text/settings
* [ ] https://github.com/w3c/charter-webperf/settings
* [ ] https://github.com/w3c/clipboard-apis/settings
* [ ] https://github.com/w3c/clreq/settings
* [ ] https://github.com/w3c/dap-charter/settings
* [ ] https://github.com/w3c/deviceorientation/settings
* [ ] https://github.com/w3c/DOM-Parsing/settings
* [ ] https://github.com/w3c/editing/settings
* [ ] https://github.com/w3c/editing/settings
* [ ] https://github.com/w3c/FileAPI/settings
* [ ] https://github.com/w3c/gamepad/settings
* [ ] https://github.com/w3c/html-aria/settings
* [ ] https://github.com/w3c/imsc/settings
* [ ] https://github.com/w3c/IndexedDB/settings
* [ ] https://github.com/w3c/low-vision-a11y-tf/settings
* [ ] https://github.com/w3c/mailing-list-archives/settings
* [ ] https://github.com/w3c/media-playback-quality/settings
* [ ] https://github.com/w3c/media-source/settings
* [ ] https://github.com/w3c/mediasession/settings
* [ ] https://github.com/w3c/Mobile-A11y-Extension/settings
* [ ] https://github.com/w3c/Mobile-A11y-TF-Note/settings
* [ ] https://github.com/w3c/modern-tooling/settings
* [ ] https://github.com/w3c/network-error-logging/settings
* [ ] https://github.com/w3c/perf-timing-primer/settings
* [ ] https://github.com/w3c/pointerlock/settings
* [ ] https://github.com/w3c/predefined-counter-styles/settings
* [ ] https://github.com/w3c/presentation-api/settings
* [ ] https://github.com/w3c/push-api/settings
* [ ] https://github.com/w3c/rangefinder/settings
* [ ] https://github.com/w3c/remote-playback/settings
* [ ] https://github.com/w3c/reporting/settings
* [ ] https://github.com/w3c/screen-orientation/settings
* [ ] https://github.com/w3c/selection-api/settings
* [ ] https://github.com/w3c/tr-design/src/settings
* [ ] https://github.com/w3c/tt-profile-registry/settings
* [ ] https://github.com/w3c/ttml-webvtt-mapping/settings
* [ ] https://github.com/w3c/ttml1/settings
* [ ] https://github.com/w3c/typography/settings
* [ ] https://github.com/w3c/UAAG/settings
* [ ] https://github.com/w3c/UAAG-Implementations/settings
* [ ] https://github.com/w3c/uievents/settings
* [ ] https://github.com/w3c/uievents-code/settings
* [ ] https://github.com/w3c/uievents-key/settings
* [ ] https://github.com/w3c/unspecified-web/settings
* [ ] https://github.com/w3c/using-aria/settings
* [ ] https://github.com/w3c/vctf/settings
* [ ] https://github.com/w3c/vr-workshop/settings
* [ ] https://github.com/w3c/w3c-api/settings
* [ ] https://github.com/w3c/wai-eval-tools/settings
* [ ] https://github.com/w3c/wai-inclusion/settings
* [ ] https://github.com/w3c/wai-quick-start/settings
* [ ] https://github.com/w3c/wai-resources/settings
* [ ] https://github.com/w3c/wbs-design/html/settings
* [ ] https://github.com/w3c/wcag/guidelines/settings
* [ ] https://github.com/w3c/web-annotation/settings
* [ ] https://github.com/w3c/web-nfc/settings
* [ ] https://github.com/w3c/web-share/settings
* [ ] https://github.com/w3c/webappsec-feature-policy/settings
* [ ] https://github.com/w3c/webauthn/settings
* [ ] https://github.com/w3c/webidl2.js/checker/settings
* [ ] https://github.com/w3c/webperf-dashboard/settings
* [ ] https://github.com/w3c/webrtc-charter/settings
* [ ] https://github.com/webassembly/spec/settings
* [ ] https://github.com/wicg/aom/settings
* [ ] https://github.com/wicg/background-fetch/settings
* [ ] https://github.com/wicg/BackgroundSync/spec/settings
* [ ] https://github.com/wicg/ContentPerformancePolicy/settings
* [ ] https://github.com/wicg/cookie-store/settings
* [ ] https://github.com/mikewest/cors-rfc1918/settings
* [ ] https://github.com/wicg/directory-upload/settings
* [ ] https://github.com/wicg/entries-api/settings
* [ ] https://github.com/wicg/frame-timing/settings
* [ ] https://github.com/wicg/get-installed-related-apps/settings
* [ ] https://github.com/wicg/native-file-system/settings
* [ ] https://github.com/wicg/netinfo/settings
* [ ] https://github.com/wicg/serial/settings
* [ ] https://github.com/wicg/visual-viewport/settings

(there are probably more since some repos use a non github.io URL for their homepageUrl, and many repos don't set `homepageUrl` even if they use github pages)

**Comment by dontcallmedom** [comment]
A more exhaustive look at all repos created before June 2016 and testing if they have a matching `github.io` URL yields the following list that needs fixing:
* [ ] https://github.com/w3c/2dcontext/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/a11ySlackers/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/activitystreams/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/alreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/alt-techniques/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/animation-timing/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/apiary/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/automotive/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/automotive-bg/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/blockchain/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/bp-i18n-specdev/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/csvw/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/data-shapes/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/developers/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dom/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-accessibility/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-annotation/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-charter/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-content-and-markup/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-metadata/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-pagination/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-pwp/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-pwp-arch/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-pwp-loc/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dpub-stem/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/dwbp/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/EasyChecks/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/editing-apis/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/elements-of-html/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/elreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/emma/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/epubweb/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/eventsource/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/filesystem-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/findtext/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/fingerprinting-guidance/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/geofencing-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/gh-issue-dashboard/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/github-notify-ml-config/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/hcls/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/hcls-fhir-rdf/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/html-cr-exit/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/html-landscape/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/html-normative-references/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/html-reference/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/html-transcript/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/i18n-activity/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/i18n-discuss/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/i18n-drafts/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/ilreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/ime-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/IntersectionObserver/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/klreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/ldp-testsuite/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/locadd/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/low-vision-SC/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/LRS/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/ltli/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/manifest-csp/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/mathml/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/mediartc-roadmap-ui/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/microdata-rdf/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/mlreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/mmi-discovery/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/Mobile-A11y-Extension/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/motion-path/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/musicxml/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/netinfo/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/nfc/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/node-w3capi/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/omn/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/packaged-webapps/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/payment-method-credit-transfer/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/perf-security-privacy/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/pfwg/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/poe/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/privacy-considerations/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/publ-epub-revision/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/quota-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/rangefinder/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/rdf-tests/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/respec/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/respec-docs/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/rqtf/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/scholarly-html/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/sdw/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/setImmediate/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/share-psi/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/ShEx/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/smufl/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/standards-track/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/streams-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/svgwg/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/swig/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/test-results/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/timed-text-dashboard/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/tlreq/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/tpac2016/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/tvcontrol-api/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/UAAG-Implementations/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/unicode-xml/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/unspecified-web/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/vctf/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/vr-workshop/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/w3c-waet/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/wai-gh-training-2015-06-29/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/wai-planning-and-implementation/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/wai-wcag-quickref/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/wai-website-design/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/wcag-em-report-tool/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/Web-and-TV-IG/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/web-animations/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/web-performance/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/webcomponents/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/webmessaging/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/webpayments-ig/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/WebPlatformWG/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/websockets/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/webstorage/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/workers/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/writing-accessible-svg/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/xml-entities/settings#pages-https-redirect-feature
* [ ] https://github.com/w3c/XMLHttpRequest/settings#pages-https-redirect-feature
* [ ] https://github.com/w3ctag/tagdocs/settings#pages-https-redirect-feature
* [ ] https://github.com/WebAudio/demo-list/settings#pages-https-redirect-feature
* [ ] https://github.com/WebAudio/web-midi-api/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/admin/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/container-queries/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/ContentPerformancePolicy/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/CSS-Parser-API/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/directory-upload/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/EventListenerOptions/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/historical-a11yapi/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/historical-web-payments-browser-api/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/hsts-priming/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/img-conversion/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/indexed-db-observers/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/InputDeviceCapabilities/settings#pages-https-redirect-feature
* [ ] https://github.com/WICG/ResizeObserver/settings#pages-https-redirect-feature

**Comment by dontcallmedom** [comment]
Only one that I couldn't handle myself - raised an issue for it https://github.com/w3ctag/tagdocs/issues/1 ; closing this one.
